name: the_only
description: Unified The Only media application.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  video_player: ^2.14.0
  webview_flutter: ^4.13.0
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
