import 'package:flutter/material.dart';
import '../../core/domain/live_channel.dart';
import '../../core/domain/models.dart';
import '../../core/domain/programme.dart';
import '../../core/player/playback_screen.dart';
import 'live_tv_controller.dart';
typedef LiveTvPlayerLauncher=Future<void> Function(BuildContext context,LiveChannel channel,StreamSource source);
class LiveTvScreen extends StatefulWidget{const LiveTvScreen({super.key,required this.controller,this.playerLauncher});final LiveTvController controller;final LiveTvPlayerLauncher? playerLauncher;@override State<LiveTvScreen> createState()=>_LiveTvScreenState();}
class _LiveTvScreenState extends State<LiveTvScreen>{List<LiveChannel> _channels=const[];List<Programme> _guide=const[];List<StreamSource> _streams=const[];LiveChannel? _selected;bool _busy=false;String? _error;
@override void initState(){super.initState();_loadChannels();}
Future<void> _loadChannels()async{setState((){_busy=true;_error=null;});try{final c=await widget.controller.channels();if(!mounted)return;setState(()=>_channels=c);}catch(_){if(mounted)setState(()=>_error='Unable to load channels');}finally{if(mounted)setState(()=>_busy=false);}}
Future<void> _open(LiveChannel channel)async{setState((){_busy=true;_error=null;_selected=channel;_guide=const[];_streams=const[];});final now=DateTime.now();try{final r=await Future.wait([widget.controller.guide(channel.epgId??channel.id,now.subtract(const Duration(hours:2)),now.add(const Duration(hours:12))),widget.controller.streams(channel)]);if(!mounted)return;setState((){_guide=r[0] as List<Programme>;_streams=r[1] as List<StreamSource>;});}catch(_){if(mounted)setState(()=>_error='Unable to load channel details');}finally{if(mounted)setState(()=>_busy=false);}}
Future<void> _launchPlayer(LiveChannel channel,StreamSource source)async{final launcher=widget.playerLauncher;if(launcher!=null){await launcher(context,channel,source);return;}await Navigator.of(context).push(MaterialPageRoute(builder:(_)=>PlaybackScreen(source:source,title:channel.name)));}
Future<void> _watch(LiveChannel channel,StreamSource source)async{setState((){_busy=true;_error=null;});try{final resolved=await widget.controller.resolveForWatch(channel,source);if(!mounted)return;if(resolved==null){setState(()=>_error='Selected stream could not be resolved safely');return;}await _launchPlayer(channel,resolved);}catch(_){if(mounted)setState(()=>_error='Live stream playback failed');}finally{if(mounted)setState(()=>_busy=false);}}
@override Widget build(BuildContext context)=>ListView(key:const Key('live-tv-screen'),padding:const EdgeInsets.all(16),children:[Row(children:[Text('Live TV',style:Theme.of(context).textTheme.headlineSmall),const Spacer(),IconButton(key:const Key('live-tv-refresh'),tooltip:'Refresh channels',onPressed:_busy?null:_loadChannels,icon:const Icon(Icons.refresh))]),if(_busy)const LinearProgressIndicator(key:Key('live-tv-loading')),if(_error!=null)Semantics(liveRegion:true,child:Text(_error!,key:const Key('live-tv-error'))),if(_channels.isEmpty&&!_busy&&_error==null)const Text('No channels available',key:Key('live-tv-empty')),for(final channel in _channels)ListTile(key:Key('live-channel-${channel.id}'),title:Text(channel.name),subtitle:channel.group==null?null:Text(channel.group!),selected:_selected?.id==channel.id,onTap:()=>_open(channel)),if(_selected case final channel?)...[const Divider(),Text(channel.name,style:Theme.of(context).textTheme.titleLarge),if(_guide.isNotEmpty)...[const SizedBox(height:8),Text('Guide',style:Theme.of(context).textTheme.titleMedium),for(final p in _guide.take(6))ListTile(dense:true,key:Key('live-programme-${p.startsAt.millisecondsSinceEpoch}'),title:Text(p.title),subtitle:Text('${p.startsAt.toLocal()} – ${p.endsAt.toLocal()}'))],const SizedBox(height:8),Text('Streams',style:Theme.of(context).textTheme.titleMedium),if(_streams.isEmpty&&!_busy&&_error==null)const Text('No playable streams available',key:Key('live-streams-empty')),for(var i=0;i<_streams.length;i++)ListTile(key:Key('live-stream-$i'),title:Text(_streams[i].quality??_streams[i].protocol.name.toUpperCase()),subtitle:Text(_streams[i].providerId),trailing:FilledButton.icon(key:Key('live-watch-$i'),onPressed:_busy?null:()=>_watch(channel,_streams[i]),icon:const Icon(Icons.play_arrow),label:const Text('Watch')))]]);
}
